detection:
  # Options: "spacy", "stanza", "transformer"
  ner_model: spacy
  # Custom regex for specific entity types
  regex_patterns:
    EMAIL: "\\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Z|a-z]{2,}\\b"
    PHONE: "\\b(\\+\\d{1,3})[-.\\s]?(\\d{2,4})[-.\\s]?(\\d{3,4})[-.\\s]?(\\d{3,8})\\b"
    CREDIT_CARD: "\\b(?:\\d[ -]*?){13,16}\\b"
  # "regex" | "ner" — which to trust when overlap
  priority: regex

sanitization:
  # Options: tokenize, pseudonymize, redact, generalize, fpe, aes, dp
  entity_strategies:
    PERSON: dp
    ORG: pseudonymize
    GPE: tokenize
    LOC: tokenize
    DATE: pseudonymize
    TIME: redact
    NORP:
    FAC:
    PRODUCT:
    EVENT:
    WORK_OF_ART:
    LAW:
    LANGUAGE:
    PERCENT:
    QUANTITY:
    ORDINAL:
    CARDINAL:
    MONEY: generalize
    EMAIL: fpe
    PHONE: fpe
    CREDIT_CARD: redact

  technique_params:
    encrypt:
      # use 256-bit (32-byte) key
      key: "b1d706d709f60500bf9ec3e5883567f8"
      alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890!@#$%^&*()-_+=|\\[]{}\"':;/?.>,<"
      # Options: FPE, AES
      method: FPE
    dp:
      text_perturb:
        enable: true
        epsilon: 1.0
        protected_entity_types: ["PERSON"]
      label_perturb:
        enable: true
        epsilon: 0.5

processing:
  batch_size: 1000
  output_format: csv
  deanonymization_store: true
